# Copyright 2023 Intrinsic Innovation LLC

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "object_reference_utils",
    srcs = ["object_reference_utils.cc"],
    hdrs = ["object_reference_utils.h"],
    deps = [
        "//intrinsic/world/proto:object_world_refs_cc_proto",
    ],
)
