// Copyright 2023 Intrinsic Innovation LLC

syntax = "proto3";

package intrinsic_proto.conductor;

import "google/longrunning/operations.proto";
import "google/protobuf/empty.proto";
import "intrinsic/conductor/proto/execution_context.proto";
import "intrinsic/conductor/proto/save_status.proto";
import "intrinsic/config/proto/operation_mode.proto";
import "intrinsic/executive/proto/run_metadata.proto";
import "intrinsic/scene/proto/v1/scene_object_updates.proto";

option go_package = "intrinsic/conductor/proto/conductor_go_proto";

// Manages application state in a running application.
//
// Handles the correspondence between the world service, executive, simulation,
// and application data.
service ConductorService {
  ///////////////////////////////////////////////////////////////////////////
  //
  // Solution lifetime routines
  //
  ///////////////////////////////////////////////////////////////////////////

  // Notifies the conductor that we've started a solution. This prompts the
  // conductor to maintain state about the currently running solution that is
  // relevant to this particular deployment (such as which world is the belief
  // world).
  rpc StartSolution(StartSolutionRequest) returns (StartSolutionResponse) {}

  // Notifies the conductor that we've stopped a solution. This prompts the
  // conductor to clean up state about the currently running solution.
  // Note that if a long running operation started with PrepareProcessStart is
  // in progress, it will be cancelled.
  rpc StopSolution(StopSolutionRequest) returns (StopSolutionResponse) {}

  ///////////////////////////////////////////////////////////////////////////
  //
  // Process lifetime routines
  //
  ///////////////////////////////////////////////////////////////////////////

  // Called prior to the executive starting a process. Signals to the conductor
  // that it may need to reset belief world and simulation if we are running in
  // sim. See PrepareProcessStartRequest for more details on the behavior of
  // this RPC depending on the request parameters.
  // Returns a long running operation that can be used to check the status of
  // the operation (see GetOperation and CancelOperation). It is only safe to
  // start the process once the operation is done and its result is not an
  // error.
  rpc PrepareProcessStart(PrepareProcessStartRequest)
      returns (google.longrunning.Operation) {
    option (google.longrunning.operation_info) = {
      response_type: "PrepareProcessStartResponse"
      metadata_type: "PrepareProcessStartMetadata"
    };
  }

  // Get a particular operation by name.
  // The returned operation can be used to:
  // - check whether it has completed (the `done` field will be true)
  // - access the result when done (`error` or `response` field set)
  // Note that operations started with PrepareProcessStart that have completed
  // are cleaned up when PrepareProcessStart is called again, and will not be
  // available.
  rpc GetOperation(google.longrunning.GetOperationRequest)
      returns (google.longrunning.Operation) {}

  // Starts asynchronous cancellation on a long-running operation. Clients can
  // use GetOperation to check whether the cancellation succeeded or whether the
  // operation completed despite cancellation. On successful cancellation, the
  // operation will have an [Operation.error][] value with a
  // [google.rpc.Status.code][] of 1, corresponding to `Code.CANCELLED`.
  rpc CancelOperation(google.longrunning.CancelOperationRequest)
      returns (google.protobuf.Empty) {}

  // Called by the executive prior to resuming a process after being in a paused
  // state.
  rpc PrepareProcessResume(PrepareProcessResumeRequest)
      returns (PrepareProcessResumeResponse) {}

  // Called when the executive has stopped running all processes (processes may
  // either be in a suspended or terminal state).
  // Note that if a long running operation started with PrepareProcessStart is
  // in progress, it will be cancelled.
  rpc NotifyAllProcessesStopped(NotifyAllProcessesStoppedRequest)
      returns (NotifyAllProcessesStoppedResponse) {}

  ///////////////////////////////////////////////////////////////////////////
  //
  // Direct world management routines
  //
  ///////////////////////////////////////////////////////////////////////////

  // Saves a world to the application. For now, this operation simply copies the
  // world with the specified ID into the resource set.
  rpc SaveWorld(SaveWorldRequest) returns (SaveWorldResponse) {}

  // Restores a world in the world service from the resource set of the
  // application.
  rpc RestoreWorld(RestoreWorldRequest) returns (RestoreWorldResponse) {}

  // Resets the application such that the current belief world reflects the
  // specified world. The belief world ID comes from the current execution
  // context. Additionally resets simulation with the belief world as
  // the initial state.
  rpc Reset(ResetRequest) returns (ResetResponse) {}

  // Queries the conductor for the latest save status, where it will compare the
  // world ID against the world that would have been created from the current
  // value of the resource set.
  rpc GetSaveStatus(GetSaveStatusRequest) returns (GetSaveStatusResponse) {}

  ///////////////////////////////////////////////////////////////////////////
  //
  // Direct asset management routines
  //
  ///////////////////////////////////////////////////////////////////////////

  // Updates the configuration for a scene object with the given update, and
  // converts that update to a world update to make sure that the existing
  // belief and init worlds reflect the configuration change.
  rpc ConfigureSceneObject(ConfigureSceneObjectRequest)
      returns (ConfigureSceneObjectResponse) {}

  ///////////////////////////////////////////////////////////////////////////
  //
  // Executive context queries
  //
  ///////////////////////////////////////////////////////////////////////////

  // Returns the current execution context of the executive.
  rpc GetExecutionContext(GetExecutionContextRequest)
      returns (ExecutionContext) {}
}

message StartSolutionRequest {
  // The operation mode of the context within which this solution was started.
  config.OperationMode operation_mode = 1;

  // Whether to skip invalid world updates on start solution.
  bool skip_invalid_world_updates = 2;
}

message StartSolutionResponse {}

message StopSolutionRequest {}

message StopSolutionResponse {}
message PrepareProcessStartRequest {
  message ProcessInfo {
    // The state that the process is in.
    intrinsic_proto.executive.RunMetadata.State state = 1;

    // The world ID of the initial world of this process.
    string init_world_id = 2;
  }

  // The world to use to seed the belief world with. If this is empty, the
  // conductor will not reset the belief world or simulation.
  string init_world_id = 1;

  // Relevant information about other processes that are running in the
  // executive. The conductor has a single execution context (belief world and
  // simulator, if the solution is running in sim), so it uses this information
  // to determine how to update the execution context. It does one of the
  // following if init_world_id is not empty:
  // - If other_process_info does not have any process in an ACTIVE state, the
  //   execution context is reset from the passed init world.
  // - If other_process_info has at least one process in ACTIVE state,
  //   - If the init_world_id is different from the init_world_id of the ACTIVE
  //     process, an error is returned.
  //   - Otherwise, the execution context is not reset. If the solution is
  //     running in sim, then simulation is unpaused.
  // For the purpose of PrepareProcessStart, a process is considered ACTIVE if
  // it is in a PREPARING, RUNNING, CANCELING, SUSPENDING, or SUSPENDED state.
  repeated ProcessInfo other_process_info = 2;
}

message PrepareProcessStartResponse {
  // The ID in the world service of the belief world to use in this running
  // process.
  string belief_world_id = 1;

  // The ID in the world service of the simulated world that will be used in
  // this running process.
  string sim_world_id = 2;
}

// Metadata for a PrepareProcessStart operation.
message PrepareProcessStartMetadata {}

message NotifyAllProcessesStoppedRequest {}

message NotifyAllProcessesStoppedResponse {}

message PrepareProcessResumeRequest {}

message PrepareProcessResumeResponse {}

message SaveWorldRequest {
  // The world in the world service that we will save to the resource set.
  string id = 1;
}

message SaveWorldResponse {}

message RestoreWorldRequest {
  // The world in the world service that we will restore the resource set to.
  string id = 1;
}

message RestoreWorldResponse {}

message GetSaveStatusRequest {
  // The world ID that we want to check against the stored resource set.
  string id = 1;
}

message GetSaveStatusResponse {
  SaveState state = 1;
}

message ResetRequest {
  // The world in the world service that we will restore the resource set to.
  string edit_world_id = 1;

  reserved "sim_world_id", "belief_world_id";
  reserved 2, 3;
}

message ResetResponse {}

message ConfigureSceneObjectRequest {
  // The name of the asset instance representing the scene object.
  string name = 1;

  // The scene object update configuration to apply to the given scene object.
  intrinsic_proto.scene_object.v1.SceneObjectInstanceUpdate update = 2;
}

message ConfigureSceneObjectResponse {}

message GetExecutionContextRequest {}
