// Copyright 2023 Intrinsic Innovation LLC

syntax = "proto3";

package intrinsic_proto.conductor;

option go_package = "intrinsic/conductor/proto/conductor_go_proto";

// Manages worlds in the solution.
//
// Handles the correspondence between the world service, executive, simulation,
// and solution data.
service ConductorService {
  // Resets the solution's runtime state such that the current belief world
  // reflects the specified world. The belief world ID comes from the current
  // execution context. Additionally resets simulation with the belief world as
  // the initial state.
  rpc Reset(ResetRequest) returns (ResetResponse) {}

}

message ResetRequest {
  // The world in the world service that we will restore the worlds to.
  string edit_world_id = 1;

  reserved "sim_world_id", "belief_world_id";
  reserved 2, 3;
}

message ResetResponse {}
