# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//bazel:go_macros.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "auth",
    srcs = [
        "auth.go",
        "cloud.go",
        "perrpccreds.go",
        "shared.go",
        "token_source.go",
        "tokenshttp.go",
    ],
    importpath = "intrinsic/tools/inctl/auth/auth",
    deps = [
        "//intrinsic/config:environments",
        "//intrinsic/kubernetes/acl:cookies",
        "//intrinsic/kubernetes/acl:identity",
        "//intrinsic/kubernetes/acl:jwt",
        "//intrinsic/tools/inctl/util:vmalias",
        "@com_github_cenkalti_backoff_v4//:go_default_library",
        "@com_github_golang_glog//:go_default_library",
        "@com_github_spf13_viper//:go_default_library",
        "@io_opencensus_go//plugin/ocgrpc:go_default_library",
        "@org_golang_google_grpc//:go_default_library",
        "@org_golang_google_grpc//credentials:go_default_library",
        "@org_golang_google_grpc//metadata:go_default_library",
    ],
)

go_library(
    name = "authtest",
    testonly = True,
    srcs = ["authtest.go"],
    importpath = "intrinsic/tools/inctl/auth/authtest",
    deps = [":auth"],
)
