# Copyright 2023 Intrinsic Innovation LLC

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "scene_object_bzl",
    srcs = ["scene_object.bzl"],
    visibility = ["//intrinsic:intrinsic_internal"],
    deps = [
        "//intrinsic/util/proto/build_defs:descriptor_set",
    ],
)
