// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.motion_planning.v1;

import "intrinsic/icon/proto/joint_space.proto";
import "intrinsic/world/proto/object_world_refs.proto";

option go_package = "intrinsic/motion_planning/proto/v1/robot_specification_go_proto";

message RobotReference {
  oneof robot_reference {
    // Must have ObjectType==ROBOT_PART.
    intrinsic_proto.world.ObjectReference object_id = 1;
  }
}

// Contains all relevant information to identify the robot that is being
// controlled and sets robot specific parameters used for planning.
message RobotSpecification {
  // Specification of what robot is being controlled.
  RobotReference robot_reference = 1;

  // Starting joint configuration of the robot. If not set, the
  // current position in the world will be used.
  optional intrinsic_proto.icon.JointVec start_configuration = 2;

  reserved 3, 4;
  reserved "l1_joint_limits", "default_cartesian_limits";
}
