# Copyright 2023 Intrinsic Innovation LLC

load("//bazel:go_macros.bzl", "go_library")

package(default_visibility = ["//intrinsic:public_api_users"])

go_library(
    name = "errors",
    srcs = ["errors.go"],
    importpath = "intrinsic/assets/validation/errors",
)
