# Copyright 2023 Intrinsic Innovation LLC

load("//bazel:go_macros.bzl", "go_library")

go_library(
    name = "intrinsic",
    srcs = ["init.go"],
    importpath = "intrinsic/production/intrinsic",
    visibility = ["//intrinsic:intrinsic_internal"],
)
