# Copyright 2023 Intrinsic Innovation LLC

# proto-file: intrinsic/assets/data/proto/v1/data_manifest.proto
# proto-message: intrinsic_proto.data.v1.DataManifest

metadata {
  id {
    package: "ai.intrinsic"
    name: "calculator_config_data"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "Calculator config data."
  }
  display_name: "Calculator Config"
}
data {
  [type.googleapis.com/intrinsic_proto.services.CalculatorConfig] {
    reverse_order: false
    conversion_dataset {
      name: "ai.intrinsic.units_conversion_data"
    }
  }
}
