# Copyright 2023 Intrinsic Innovation LLC

load("//bazel:go_macros.bzl", "go_library")

package(default_visibility = [
    "//intrinsic/tools/inctl/cmd/vm:__subpackages__",
])

go_library(
    name = "defaults",
    srcs = ["defaults.go"],
    importpath = "intrinsic/kubernetes/vmpool/service/pkg/defaults/defaults",
)
