# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module(
    name = "ai_intrinsic_sdks",
    version = "",
)

non_module_deps = use_extension("//bazel:non_module_deps.bzl", "non_module_deps_ext")

######
# Go #
######

bazel_dep(name = "rules_go", version = "0.62.0", repo_name = "io_bazel_rules_go")

go_sdk = use_extension("@io_bazel_rules_go//go:extensions.bzl", "go_sdk")
go_sdk.download(version = "1.26.6")

bazel_dep(name = "gazelle", version = "0.52.2", repo_name = "bazel_gazelle")
bazel_dep(name = "gazelle_cc", version = "0.6.0")

go_deps = use_extension("@bazel_gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")

# This can be updated with buildozer
# https://github.com/bazelbuild/buildtools/blob/master/buildozer/README.md
use_repo(
    go_deps,
    "com_github_andydunstall_piko",
    "com_github_authzed_authzed_go",
    "com_github_bazelbuild_buildtools",
    "com_github_bazelbuild_remote_apis_sdks",
    "com_github_bits_and_blooms_bitset",
    "com_github_cenkalti_backoff_v4",
    "com_github_golang_glog",
    "com_github_golang_jwt_jwt_v4",
    "com_github_golang_jwt_jwt_v5",
    "com_github_google_gnostic",
    "com_github_google_go_cmp",
    "com_github_google_go_containerregistry",
    "com_github_google_safearchive",
    "com_github_google_subcommands",
    "com_github_googlecloudplatform_opentelemetry_operations_go_exporter_trace",
    "com_github_gorilla_websocket",
    "com_github_masterminds_semver",
    "com_github_mwitkow_grpc_proxy",
    "com_github_netresearch_go_cron",
    "com_github_pborman_uuid",
    "com_github_pkg_errors",
    "com_github_protocolbuffers_txtpbfmt",
    "com_github_robfig_cron_v3",
    "com_github_rs_xid",
    "com_github_spf13_cobra",
    "com_github_spf13_pflag",
    "com_github_spf13_viper",
    "com_github_stoewer_go_strcase",
    "com_github_stretchr_testify",
    "com_google_cloud_go_longrunning",
    "in_gopkg_xmlpath_v2",
    "in_gopkg_yaml_v3",
    "io_opencensus_go",
    "io_opencensus_go_contrib_exporter_ocagent",
    "io_opencensus_go_contrib_exporter_prometheus",
    "io_opentelemetry_go_contrib_instrumentation_google_golang_org_grpc_otelgrpc",
    "io_opentelemetry_go_contrib_propagators_b3",
    "io_opentelemetry_go_contrib_propagators_opencensus",
    "io_opentelemetry_go_otel",
    "io_opentelemetry_go_otel_bridge_opencensus",
    "io_opentelemetry_go_otel_sdk",
    "org_golang_google_genproto",
    "org_golang_google_genproto_googleapis_api",
    "org_golang_google_genproto_googleapis_rpc",
    "org_golang_google_grpc",
    "org_golang_google_protobuf",
    "org_golang_x_exp",
    "org_golang_x_net",
    "org_golang_x_sync",
    "org_golang_x_text",
    "org_uber_go_atomic",
)

##########
# Python #
##########
PYTHON_VERSION = "3.11"

bazel_dep(name = "rules_python", version = "1.9.2")
bazel_dep(name = "rules_uv", version = "0.89.2")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    configure_coverage_tool = True,
    python_version = PYTHON_VERSION,
)

bazel_dep(name = "pybind11_bazel", version = "3.0.1")
bazel_dep(name = "pybind11_abseil", version = "202402.0")
bazel_dep(name = "pybind11_protobuf", version = "0.0.0-20250210-f02a2b7")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "ai_intrinsic_sdks_pip_deps",
    python_version = PYTHON_VERSION,
    requirements_lock = "//:requirements.txt",
)
use_repo(pip, "ai_intrinsic_sdks_pip_deps")

#################
# C++ toolchain #
#################

bazel_dep(name = "toolchains_llvm", version = "1.7.0")

# Inspect supported toolchains at https://github.com/bazel-contrib/toolchains_llvm/blob/master/toolchain/internal/llvm_distributions.bzl
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm", dev_dependency = True)

llvm.toolchain(
    llvm_version = "21.1.0",
)

use_repo(non_module_deps, "intrinsic_llvm_sysroot")

llvm.sysroot(
    label = "@intrinsic_llvm_sysroot//:all_files",
    targets = ["linux-x86_64"],
)
use_repo(
    llvm,
    "llvm_toolchain",
)

register_toolchains(
    "@llvm_toolchain//:all",
    dev_dependency = True,
)

bazel_dep(name = "rules_cc", version = "0.2.22")

########
# Rust #
########

bazel_dep(name = "rules_rust", version = "0.69.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = [
        "1.75.0",
    ],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")


#########
# JS/TS #
#########

bazel_dep(name = "rules_nodejs", version = "6.7.5", dev_dependency = True)
bazel_dep(name = "aspect_rules_js", version = "3.4.0", dev_dependency = True)
bazel_dep(name = "aspect_rules_ts", version = "3.10.0", dev_dependency = True)
bazel_dep(name = "aspect_rules_esbuild", version = "0.27.0", dev_dependency = True)

node = use_extension("@rules_nodejs//nodejs:extensions.bzl", "node", dev_dependency = True)
node.toolchain(
    node_repositories = {
        "24.19.0-linux_amd64": [
            "node-v24.19.0-linux-x64.tar.xz",
            "node-v24.19.0-linux-x64",
            "14b342e71204f811bde6153be8e04b62aef63c236fef92b55f9c83154b409647",
        ],
    },
    node_version_from_nvmrc = "//:.nvmrc",
)

npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm", dev_dependency = True)

rules_ts_ext = use_extension("@aspect_rules_ts//ts:extensions.bzl", "ext", dev_dependency = True)

pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm", dev_dependency = True)

js_rules = use_extension("//bazel:js_rules.bzl", "js_rules")
use_repo(js_rules, "intrinsic_js_rules")


######################
# Bazel dependencies #
######################

bazel_dep(name = "abseil-cpp", version = "20250814.2")
bazel_dep(name = "abseil-py", version = "2.1.0", repo_name = "com_google_absl_py")
bazel_dep(name = "assimp", version = "6.0.3")
bazel_dep(name = "bazel_lib", version = "3.7.1")
bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "boringssl", version = "0.20260803.0")
bazel_dep(name = "cel-cpp", version = "0.14.0", repo_name = "com_google_cel_cpp")
bazel_dep(name = "cel-spec", version = "0.25.2", repo_name = "com_google_cel_spec")
bazel_dep(name = "ceres-solver", version = "2.2.0", repo_name = "com_google_ceres_solver")
bazel_dep(name = "com_github_mvukov_rules_ros2", version = "0.0.0-20260118-78d85ff")
bazel_dep(name = "dumb-init", version = "1.2.5")
bazel_dep(name = "eigen", version = "5.0.1.bcr.2", repo_name = "com_gitlab_libeigen_eigen")
bazel_dep(name = "etherlab-ethercat", version = "1.6.7.bcr.1")
bazel_dep(name = "flatbuffers", version = "25.12.19", repo_name = "com_github_google_flatbuffers")
bazel_dep(name = "fmt", version = "12.2.0")
bazel_dep(name = "fuzztest", version = "20250805.0", repo_name = "com_google_fuzztest")
bazel_dep(name = "google_benchmark", version = "1.9.5", repo_name = "com_google_benchmark")
bazel_dep(name = "google_cloud_cpp", version = "3.0.0-rc1")
bazel_dep(name = "googleapis-cc", version = "1.1.5")
bazel_dep(name = "googleapis-grpc-cc", version = "1.1.5")
bazel_dep(name = "googleapis-python", version = "1.1.5")
bazel_dep(name = "googleapis", version = "0.0.0-20260728-b8486a2f", repo_name = "com_google_googleapis")
bazel_dep(name = "googletest", version = "1.17.0.bcr.2", repo_name = "com_google_googletest")
bazel_dep(name = "grpc_ecosystem_grpc_gateway", version = "2.29.0.bcr.3", repo_name = "com_github_grpc_ecosystem_grpc_gateway_v2")
bazel_dep(name = "grpc", version = "1.74.0", repo_name = "com_github_grpc_grpc")
bazel_dep(name = "gz-math", version = "9.2.0")
bazel_dep(name = "libxml2-go", version = "0.0.0-20250331-c934e3f.bcr.1")
bazel_dep(name = "libxml2", version = "2.14.4.bcr.1")
bazel_dep(name = "libzip", version = "1.11.4.bcr.3")
bazel_dep(name = "nlohmann_json", version = "3.12.0.bcr.1", repo_name = "com_github_nlohmann_json")
bazel_dep(name = "onetbb", version = "2022.3.0")
bazel_dep(name = "opencensus-cpp", version = "0.0.0-20230502-50eb5de.bcr.2", repo_name = "io_opencensus_cpp")
bazel_dep(name = "or-tools", version = "9.15", repo_name = "or_tools")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "protobuf-matchers", version = "0.1.1", repo_name = "com_github_inazarenko_protobuf_matchers")
bazel_dep(name = "protobuf", version = "32.1", repo_name = "com_google_protobuf")
bazel_dep(name = "re2", version = "2024-07-02.bcr.1", repo_name = "com_googlesource_code_re2")
bazel_dep(name = "riegeli", version = "0.0.0-20250822-9f2744d", repo_name = "com_google_riegeli")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_swift", version = "2.9.0")  # bumping transitive dependency to resolve compatibility level conflict with flatbuffers
bazel_dep(name = "sdformat", version = "16.1.0")
bazel_dep(name = "soplex", version = "7.1.4.bcr.5")  # bumping transitive dependency to update boost to 1.89.0
bazel_dep(name = "tar.bzl", version = "0.10.8")
bazel_dep(name = "tcmalloc", version = "0.0.0-20250927-12f2552")
bazel_dep(name = "tinygltf", version = "2.9.6")
bazel_dep(name = "tinyxml2", version = "10.0.0")
bazel_dep(name = "websocketpp", version = "0.8.2.bcr.6")  # bumping transitive dependency to update boost to 1.89.0
bazel_dep(name = "zenoh-c", version = "1.7.2.bcr.1")
bazel_dep(name = "zenoh-cpp", version = "1.7.2.bcr.1")


# We require an override to support a single patch for compatibility with aspect_rules_js v3. The
# patch is merged upstream but has not been released.
archive_override(
    module_name = "flatbuffers",
    integrity = "sha256-+BwxYrEEb+i4S5oNvdOD4k/bz4hYO5y2Ao+Q0E2QaWo=",
    remote_patch_strip = 1,
    remote_patches = {
        "https://github.com/google/flatbuffers/commit/c21bda16493fbf3586820c2f5f952399329f674a.patch": "sha256-e7vj8dq4BP14xUIl7AonJbVMCFgDVkV5xN+QqXq+1ts=",
    },
    strip_prefix = "flatbuffers-25.12.19",
    url = "https://github.com/google/flatbuffers/archive/refs/tags/v25.12.19.tar.gz",
)


##############
# Containers #
##############

bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "container_structure_test", version = "1.22.1")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

oci.pull(
    name = "distroless_base",
    digest = "sha256:57c1e4c72feb5925c4763ae4f6bd2013ad3854f57eff5b60dd9acb1ce0abc66e",
    image = "gcr.io/distroless/base",
    platforms = ["linux/amd64"],
)

# Version pinned to last known version for EC-Engineer, due to b/478927987.
oci.pull(
    name = "distroless_base_bookworm",
    digest = "sha256:9e9b50d2048db3741f86a48d939b4e4cc775f5889b3496439343301ff54cdba8",
    image = "gcr.io/distroless/base",
    platforms = ["linux/amd64"],
    tag = "bookworm",
)
oci.pull(
    name = "distroless_cc",
    digest = "sha256:ed7c407fd64eb0af9dddb9456b94cee188a40a7f53cf38c9836e1e9ae14fca02",
    image = "gcr.io/distroless/cc",
    platforms = ["linux/amd64"],
)
oci.pull(
    name = "distroless_python3",
    digest = "sha256:178dd00f2da3271f3819df5cd327472754946c7430d82197b247e95e839a3d55",
    image = "gcr.io/distroless/python3",
    platforms = ["linux/amd64"],
)
oci.pull(
    name = "zenohd",
    digest = "sha256:9a8195c927169365e516309d55753b9c3a7484a59825cf4fbefb9125cfbdb01d",
    image = "us-central1-docker.pkg.dev/intrinsic-mirror/intrinsic-build-images/zenohd:1.7.2",
    platforms = ["linux/amd64"],
)

# NOTE: Bazel reports wrong usage of the repos as a warning
# BUG: https://github.com/bazel-contrib/rules_oci/issues/727
use_repo(
    oci,
    "distroless_base",
    "distroless_base_bookworm",
    "distroless_base_bookworm_linux_amd64",
    "distroless_base_linux_amd64",
    "distroless_cc",
    "distroless_cc_linux_amd64",
    "distroless_python3",
    "distroless_python3_linux_amd64",
)

############################
# Missing Google OSS files #
############################

use_repo(
    non_module_deps,
)

# Needed to build rules_ros2 messages and tf2
extension_for_rules_ros2 = use_extension("@com_github_mvukov_rules_ros2//ros2:extensions.bzl", "non_module_deps")
use_repo(
    extension_for_rules_ros2,
    "ros2_common_interfaces",
    "ros2_geometry2",
    "ros2_rcl_interfaces",
    "ros2_rclcpp",
    "ros2_rclpy",
    "ros2_rcutils",
    "ros2_rmw",
    "ros2_rosbag2",
    "ros2_rosidl",
    "ros2_rosidl_typesupport",
)

# Temporary patch to make rclpy compatible with our LLVM toolchain.
# Can be removed when https://github.com/bazelbuild/bazel-central-registry/pull/9746
# is merged and the new version is available in the BCR.
single_version_override(
    module_name = "com_github_mvukov_rules_ros2",
    patch_strip = 1,
    patches = ["//third_party/rules_ros2:rules_ros2_atomic.patch"],
)

single_version_override(
    module_name = "zenoh-c",
    patch_strip = 1,
    patches = ["//third_party/zenohc:static.patch"],
)

npm.npm_translate_lock(
    name = "npm",
    data = [
        "//intrinsic/frontend/sdk:package.json",
        "//intrinsic/frontend/sdk:pnpm-workspace.yaml",
    ],
    pnpm_lock = "//intrinsic/frontend/sdk:pnpm-lock.yaml",
)
use_repo(npm, "npm")
rules_ts_ext.deps(
    name = "npm_typescript",
    ts_version_from = "//intrinsic/frontend/sdk:package.json",
)
use_repo(rules_ts_ext, "npm_typescript")
pnpm.pnpm(pnpm_version_from = "//intrinsic/frontend/sdk:package.json")
use_repo(pnpm, "pnpm")

register_toolchains("//intrinsic/frontend/sdk:gen_es_toolchain_toolchain", dev_dependency = True)

# Intrinsic APIs bazel module (this will become an external module outside of insrc in the future)
bazel_dep(name = "intrinsic_apis", version = "0.0.1")
local_path_override(
    module_name = "intrinsic_apis",
    path = "intrinsic/intrinsic_apis",
)
