// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.services.v1;

import "google/protobuf/any.proto";

option go_package = "intrinsic/assets/services/proto/v1/dynamic_reconfiguration_go_proto";

// Supports modifying the configuration of a Service without restarting it.
service DynamicReconfiguration {
  // Applies a new Service configuration.
  rpc ApplyConfiguration(ApplyConfigurationRequest)
      returns (ApplyConfigurationResponse) {}
}

message ApplyConfigurationRequest {
  // The configuration to apply.
  google.protobuf.Any configuration = 1;
}

message ApplyConfigurationResponse {}

// Configuration for the dynamic reconfiguration interfaces provided to the
// Intrinsic platform.
message DynamicReconfigurationConfig {
  enum ServiceVersion {
    UNSPECIFIED = 0;
    // The service implements
    // intrinsic_proto.services.v1.DynamicReconfiguration.
    INTRINSIC_PROTO_SERVICES_V1_DYNAMIC_RECONFIGURATION = 1;
  }
  // The list of dynamic reconfiguration services provided to the platform.
  // Authors might choose to implement multiple versions to increase
  // compatibility across a wider range of platform versions.
  repeated ServiceVersion service_versions = 1;
}
