# Copyright 2023 Intrinsic Innovation LLC

# proto-file: google/protobuf/any.proto
# proto-message: google.protobuf.Any

[type.googleapis.com/intrinsic_proto.icon.HardwareModuleConfig] {
  module_config {
    [type.googleapis.com/intrinsic_proto.icon.LoopbackConfig] {
      # Empty, but needs to be there and have the correct type
    }
  }
  drives_realtime_clock: false
  control_frequency_hz: 250
}
