// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package telemetry

import (
	"context"
	"net/http"
	"strconv"
	"strings"
	"sync/atomic"
	"time"

	"go.opencensus.io/plugin/ocgrpc"
	"go.opencensus.io/stats"
	"go.opencensus.io/tag"
	"go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	grpcstats "google.golang.org/grpc/stats"
	"google.golang.org/grpc/status"
)

var opencensusRPCDataKey = &struct{}{}

// pathSpanNameFormatter names HTTP spans after the request path, which is what
// ochttp used to do. Without it otelhttp gives every request the same static
// name, such as "HTTP GET".
func pathSpanNameFormatter(_ string, r *http.Request) string {
	if r == nil || r.URL == nil || r.URL.Path == "" {
		return "/"
	}
	return r.URL.Path
}

// NewOtelGRPCServerOptions returns a list of grpc.ServerOption configuring gRPC
// StatsHandlers for OpenTelemetry tracing and backwards-compatible OpenCensus metrics.
func NewOtelGRPCServerOptions(opts ...otelgrpc.Option) []grpc.ServerOption {
	defaults := []otelgrpc.Option{otelgrpc.WithPropagators(GRPCPropagator)}
	return []grpc.ServerOption{
		grpc.StatsHandler(otelgrpc.NewServerHandler(append(defaults, opts...)...)),
		grpc.StatsHandler(NewOpencensusMetricsHandler()),
	}
}

// NewOtelGRPCClientOptions returns a list of grpc.DialOption configuring a gRPC
// StatsHandler for OpenTelemetry tracing.
func NewOtelGRPCClientOptions(opts ...otelgrpc.Option) []grpc.DialOption {
	defaults := []otelgrpc.Option{otelgrpc.WithPropagators(GRPCPropagator)}
	return []grpc.DialOption{
		grpc.WithStatsHandler(otelgrpc.NewClientHandler(append(defaults, opts...)...)),
	}
}

// NewOtelHTTPHandler wraps handler with OpenTelemetry server instrumentation.
func NewOtelHTTPHandler(handler http.Handler, opts ...otelhttp.Option) http.Handler {
	defaults := []otelhttp.Option{
		otelhttp.WithPropagators(HTTPPropagator),
		otelhttp.WithSpanNameFormatter(pathSpanNameFormatter),
	}
	return otelhttp.NewHandler(
		handler,
		"", // Unused: the span name formatter above takes precedence.
		append(defaults, opts...)...,
	)
}

// NewOtelHTTPTransport wraps base with OpenTelemetry client instrumentation.
//
// If base is nil, http.DefaultTransport is used.
func NewOtelHTTPTransport(base http.RoundTripper, opts ...otelhttp.Option) http.RoundTripper {
	defaults := []otelhttp.Option{
		otelhttp.WithPropagators(HTTPPropagator),
		otelhttp.WithSpanNameFormatter(pathSpanNameFormatter),
	}
	return otelhttp.NewTransport(base, append(defaults, opts...)...)
}

// NewOpencensusMetricsHandler returns a grpcstats.Handler that records metrics
// that mirror the ones previously generated by OpenCensus (ocgrpc.ServerHandler).
// Most of the code was copied to preserve backwards compatibility without OpenCensus.
func NewOpencensusMetricsHandler() grpcstats.Handler {
	return new(opencensusMetricsHandler)
}

// opencensusRPCData stores stats for a gRPC call.
// This logic mirrors metrics from OpenCensus.
type opencensusRPCData struct {
	sentBytes, recvBytes int64 // access atomically

	startTime time.Time
}

// opencensusMetricsHandler implements grpcstats.Handler to record metrics
// that mirror the ones previously generated by OpenCensus (ocgrpc.ServerHandler).
type opencensusMetricsHandler struct{}

var _ grpcstats.Handler = (*opencensusMetricsHandler)(nil)

// HandleConn exists to satisfy gRPC stats.Handler.
func (s *opencensusMetricsHandler) HandleConn(ctx context.Context, cs grpcstats.ConnStats) {
	// no-op
}

// TagConn exists to satisfy gRPC stats.Handler.
func (s *opencensusMetricsHandler) TagConn(ctx context.Context, cti *grpcstats.ConnTagInfo) context.Context {
	// no-op
	return ctx
}

// HandleRPC implements per-RPC tracing and stats instrumentation.
func (s *opencensusMetricsHandler) HandleRPC(ctx context.Context, rs grpcstats.RPCStats) {
	switch st := rs.(type) {
	case *grpcstats.OutHeader, *grpcstats.InHeader, *grpcstats.InTrailer, *grpcstats.OutTrailer, *grpcstats.Begin:
		// do nothing
	case *grpcstats.OutPayload:
		if d, ok := ctx.Value(opencensusRPCDataKey).(*opencensusRPCData); ok {
			atomic.AddInt64(&d.sentBytes, int64(st.Length))
		}
	case *grpcstats.InPayload:
		if d, ok := ctx.Value(opencensusRPCDataKey).(*opencensusRPCData); ok {
			atomic.AddInt64(&d.recvBytes, int64(st.Length))
		}
	case *grpcstats.End:
		d, ok := ctx.Value(opencensusRPCDataKey).(*opencensusRPCData)
		if !ok {
			return
		}

		elapsedTime := time.Since(d.startTime)

		var statusCode string
		if st.Error != nil {
			if s, ok := status.FromError(st.Error); ok {
				statusCode = statusCodeToString(s)
			}
		} else {
			statusCode = "OK"
		}

		latencyMillis := float64(elapsedTime) / float64(time.Millisecond)
		stats.RecordWithOptions(ctx,
			stats.WithTags(
				tag.Upsert(ocgrpc.KeyServerStatus, statusCode),
			),
			stats.WithMeasurements(
				ocgrpc.ServerSentBytesPerRPC.M(atomic.LoadInt64(&d.sentBytes)),
				ocgrpc.ServerReceivedBytesPerRPC.M(atomic.LoadInt64(&d.recvBytes)),
				ocgrpc.ServerLatency.M(latencyMillis),
			),
		)
	}
}

// TagRPC implements per-RPC context management.
func (s *opencensusMetricsHandler) TagRPC(ctx context.Context, rti *grpcstats.RPCTagInfo) context.Context {
	if rti == nil {
		return ctx
	}

	d := &opencensusRPCData{
		startTime: time.Now(),
	}

	ctx, _ = tag.New(ctx, tag.Upsert(ocgrpc.KeyServerMethod, methodName(rti.FullMethodName)))
	return context.WithValue(ctx, opencensusRPCDataKey, d)
}

func methodName(fullname string) string {
	return strings.TrimLeft(fullname, "/")
}

func statusCodeToString(s *status.Status) string {
	// see https://github.com/grpc/grpc/blob/master/doc/statuscodes.md
	switch c := s.Code(); c {
	case codes.OK:
		return "OK"
	case codes.Canceled:
		return "CANCELLED"
	case codes.Unknown:
		return "UNKNOWN"
	case codes.InvalidArgument:
		return "INVALID_ARGUMENT"
	case codes.DeadlineExceeded:
		return "DEADLINE_EXCEEDED"
	case codes.NotFound:
		return "NOT_FOUND"
	case codes.AlreadyExists:
		return "ALREADY_EXISTS"
	case codes.PermissionDenied:
		return "PERMISSION_DENIED"
	case codes.ResourceExhausted:
		return "RESOURCE_EXHAUSTED"
	case codes.FailedPrecondition:
		return "FAILED_PRECONDITION"
	case codes.Aborted:
		return "ABORTED"
	case codes.OutOfRange:
		return "OUT_OF_RANGE"
	case codes.Unimplemented:
		return "UNIMPLEMENTED"
	case codes.Internal:
		return "INTERNAL"
	case codes.Unavailable:
		return "UNAVAILABLE"
	case codes.DataLoss:
		return "DATA_LOSS"
	case codes.Unauthenticated:
		return "UNAUTHENTICATED"
	default:
		return "CODE_" + strconv.FormatInt(int64(c), 10)
	}
}
