# Copyright 2023 Intrinsic Innovation LLC

# This folder provides all the files (mostly structs) shared between the cloud side of device management and the on-prem code.

load("@io_bazel_rules_go//go:def.bzl", "go_library")

package(default_visibility = [
    "//visibility:public",
])

go_library(
    name = "shared",
    srcs = ["shared.go"],
    importpath = "intrinsic/cloud/devicemanager/shared",
)
