// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.services;

import "intrinsic/assets/proto/field_metadata.proto";
import "intrinsic/assets/proto/v1/resolved_dependency.proto";

// Configuration for the "approximate function" CustomCalculation Service.
message ApproximateFunctionConfig {
  intrinsic_proto.assets.v1.ResolvedDependency data = 2
      [(intrinsic_proto.assets.field_metadata).dependency = {
        requires: "data://intrinsic_proto.services.TwoDimensionalFunctionData",
      }];

  // The degree of the polynomial with which to approximate the function.
  //
  // If not specified, a default value of 2 will be used.
  optional int64 degree = 3;
}
