# Copyright 2023 Intrinsic Innovation LLC

# proto-file: intrinsic/assets/services/proto/service_manifest.proto
# proto-message: intrinsic_proto.services.ServiceManifest

metadata {
  id {
    package: "ai.intrinsic"
    name: "exponentiate_service"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "A custom calculate Service that exponentiates the inputs."
  }
  display_name: "Exponentiate"
}
service_def {
  service_proto_prefixes: "/intrinsic_proto.services.CustomCalculation/"
  real_spec {
    image {
      archive_filename: "exponentiate-image.tar"
    }
  }
  sim_spec {
    image {
      archive_filename: "exponentiate-image.tar"
    }
  }
}
