# proto-file: intrinsic/assets/data/proto/v1/data_manifest.proto
# proto-message: DataManifest

# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


metadata {
  id {
    package: "ai.intrinsic"
    name: "inverted_pyramid_function_data"
  }
  display_name: "Two Dimensional Inverted Pyramid Function Data"
  vendor {
    display_name: "Intrinsic"
  }
}
data {
  [type.googleapis.com/intrinsic_proto.services.TwoDimensionalFunctionData] {
    x: [-10, -10, -10, -10, -10, -5, -5, -5, -5, -5, -1, -1, -1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 5, 5, 5, 5, 5, 10, 10, 10, 10, 10]
    y: [-10, -5, 0, 5, 10, -10, -5, 0, 5, 10, -1, 0, 1, -10, -5, -1, 0, 1, 5, 10, -1, 0, 1, -10, -5, 0, 5, 10, -10, -5, 0, 5, 10]
    f: [10, 10, 10, 10, 10, 10, 5, 5, 5, 10, 1, 1, 1, 10, 5, 1, 0, 1, 5, 10, 1, 1, 1, 10, 5, 5, 5, 10, 10, 10, 10, 10, 10]
  }
}
