// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.services;

// A dataset that can be used to approximate a 2D function.
//
// Corresponding elements in the x, y, and f fields below represent a single
// set of input/output values for a function f(x, y).
message TwoDimensionalFunctionData {
  // The x-values of the function to approximate.
  repeated int64 x = 1;
  // The y-values of the function to approximate.
  repeated int64 y = 2;
  // f(x, y) for each x, y.
  repeated int64 f = 3;
}
