// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto;

option go_package = "intrinsic/kinematics/types/dynamic_limits_check_mode_go_proto";

// This enum class indicates the limits a joint position command is guaranteeing
// to abide by. For instance,
// `DYNAMIC_LIMITS_CHECK_MODE_CHECK_JOINT_ACCELERATION` denotes it should
// satisfy joint acceleration limits, while
// `DYNAMIC_LIMITS_CHECK_MODE_CHECK_NONE` will not check joint acceleration
// limits. Joint position and velocity constraints are always satisfied.
enum DynamicLimitsCheckMode {
  DYNAMIC_LIMITS_CHECK_MODE_TYPE_UNSPECIFIED = 0;
  DYNAMIC_LIMITS_CHECK_MODE_CHECK_JOINT_ACCELERATION = 1;
  DYNAMIC_LIMITS_CHECK_MODE_CHECK_NONE = 2;
}
