// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.pubsub.cloud_router_provisioner.v1;

import "intrinsic/platform/pubsub/admin_set_grpc/v1/admin_set.proto";

option go_package = "intrinsic/platform/pubsub/cloud_router_provisioner/v1/provisioner_go_proto";

// RouterProvisionRequest is the request for Provision.
message RouterProvisionRequest {
  string organization_id = 1;
}

// RouterProvisionResponse is the response for ProvisionRequest.
message RouterProvisionResponse {
  bool provisioned = 1;
}

// IsRouterProvisionedRequest is the request for IsProvisioned.
message IsRouterProvisionedRequest {
  string organization_id = 1;
}

// IsRouterProvisionedResponse is the response for IsProvisionedRequest.
message IsRouterProvisionedResponse {
  bool provisioned = 1;
}

// RouterProvisionerService is used to provision cloud router per organization.
service RouterProvisionerService {
  // IsRouterProvisioned returns true if the cloud router is already
  // provisioned for the organization.
  rpc IsRouterProvisioned(IsRouterProvisionedRequest)
      returns (IsRouterProvisionedResponse) {}

  // ProvisionRouter provisions the cloud router for the organization. It is a
  // blocking call that waits for the cloud router to be provisioned. If already
  // provisioned, it returns success immediately.
  rpc ProvisionRouter(RouterProvisionRequest)
      returns (RouterProvisionResponse) {}

  // This is a proxy method to call the AdminSetService.AdminCopy method served
  // by the cloud routers. Since there are multiple cloud routers and Ngnix
  // ingress does not support routing based on headers, we need to implement the
  // reverse proxy ourselves here.
  rpc AdminCopy(intrinsic_proto.pubsub.admin_set_grpc.v1.AdminSetRequest)
      returns (intrinsic_proto.pubsub.admin_set_grpc.v1.AdminSetResponse) {}
}
