# Copyright 2023 Intrinsic Innovation LLC

load("//intrinsic/assets/build_defs:asset.bzl", "intrinsic_asset_reference")

intrinsic_asset_reference(
    name = "calculator_scene_object_reference",
    id = "ai.intrinsic.calculator_object",
    type = "scene_object",
    version = "1.0.0",
    visibility = [
        "//visibility:public",
    ],
)
