# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//intrinsic/assets/build_defs:asset.bzl", "intrinsic_asset_reference")

intrinsic_asset_reference(
    name = "calculator_scene_object_reference",
    id = "ai.intrinsic.calculator_object",
    type = "scene_object",
    version = "1.0.0",
    visibility = [
        "//visibility:public",
    ],
)
