# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Bazel rules for generating an Intrinsic scene object.
"""

load("@bazel_lib//lib:paths.bzl", "to_rlocation_path")
load("@com_google_protobuf//bazel/common:proto_info.bzl", "ProtoInfo")
load("//intrinsic/assets/build_defs:asset.bzl", "AssetInfo", "AssetLocalInfo")
load("//intrinsic/scene/build_defs:scene_object.bzl", "SceneObjectInfo")
load("//intrinsic/util/proto/build_defs:descriptor_set.bzl", "ProtoSourceCodeInfo", "gen_source_code_info_descriptor_set")

SceneObjectTypeInfo = provider(
    "provided by intrinsic_scene_object() rule",
    fields = ["bundle_tar"],
)

def _intrinsic_scene_object_impl(ctx):
    bundle_output = ctx.outputs.bundle_out

    inputs = []
    transitive_inputs = []
    geometry_gzfiles = []

    scene_object_info = ctx.attr.scene_object[SceneObjectInfo]
    inputs.append(ctx.file.manifest)
    inputs.append(scene_object_info.gzf)
    geometry_gzfiles.append(scene_object_info.gzf)

    transitive_descriptor_sets = depset(transitive = [
        f[ProtoSourceCodeInfo].transitive_descriptor_sets
        for f in ctx.attr.deps
    ] + [scene_object_info.fdsets])
    transitive_inputs.append(transitive_descriptor_sets)

    args = ctx.actions.args().add(
        "--manifest",
        ctx.file.manifest,
    ).add(
        "--output_bundle",
        bundle_output,
    ).add_all(
        geometry_gzfiles,
        before_each = "--geometry_gzfile",
        uniquify = True,
    ).add_all(
        transitive_descriptor_sets,
        before_each = "--file_descriptor_set",
        uniquify = True,
    )

    ctx.actions.run(
        arguments = [args],
        executable = ctx.executable._sceneobjectgen,
        inputs = depset(inputs, transitive = transitive_inputs),
        mnemonic = "SceneObjectBundle",
        outputs = [bundle_output],
        progress_message = "SceneObject bundle %s" % bundle_output.short_path,
    )

    asset_info_output = ctx.actions.declare_file(ctx.label.name + ".asset_info.binpb")
    asset_local_info_output = ctx.actions.declare_file(ctx.label.name + ".asset_local_info.binpb")
    local_info_args = ctx.actions.args().add(
        "--manifest",
        ctx.file.manifest,
    ).add(
        "--asset_type",
        "ASSET_TYPE_SCENE_OBJECT",
    ).add(
        "--bundle_path",
        bundle_output,
    ).add(
        "--bundle_short_path",
        bundle_output.short_path,
    ).add(
        "--bundle_runfiles_path",
        to_rlocation_path(ctx, ctx.outputs.bundle_out),
    ).add_all(
        transitive_descriptor_sets,
        before_each = "--file_descriptor_set",
        uniquify = True,
    ).add(
        "--output_asset_info",
        asset_info_output,
    ).add(
        "--output_asset_local_info",
        asset_local_info_output,
    )
    ctx.actions.run(
        arguments = [local_info_args],
        executable = ctx.executable._assetlocalinfogen,
        inputs = depset([ctx.file.manifest], transitive = transitive_inputs),
        mnemonic = "AssetLocalInfo",
        outputs = [asset_info_output, asset_local_info_output],
        progress_message = "Writing asset local info %{output} for %{label}",
    )

    return [
        DefaultInfo(
            executable = bundle_output,
            runfiles = ctx.runfiles(
                transitive_files = depset(inputs, transitive = []),
            ),
        ),
        SceneObjectTypeInfo(
            bundle_tar = bundle_output,
        ),
        AssetInfo(
            asset_info = asset_info_output,
            transitive_descriptor_sets = transitive_descriptor_sets,
        ),
        AssetLocalInfo(
            bundle_path = bundle_output,
            local_info = asset_local_info_output,
        ),
    ]

intrinsic_scene_object = rule(
    attrs = {
        "deps": attr.label_list(
            aspects = [gen_source_code_info_descriptor_set],
            providers = [ProtoInfo],
        ),
        "manifest": attr.label(
            allow_single_file = [".textproto"],
            doc = (
                "A manifest that can be used to provide the scene object metadata."
            ),
            mandatory = True,
        ),
        "scene_object": attr.label(
            doc = (
                "The geometric description of the asset.  " +
                "This will be generated by the sdf_scene_object rule."
            ),
            mandatory = True,
            providers = [SceneObjectInfo],
        ),
        "_assetlocalinfogen": attr.label(
            cfg = "exec",
            default = Label("//intrinsic/assets/build_defs:assetlocalinfogen"),
            executable = True,
        ),
        "_sceneobjectgen": attr.label(
            cfg = "exec",
            default = Label("//intrinsic/assets/scene_objects/build_defs:sceneobjectgen_main"),
            executable = True,
        ),
    },
    outputs = {
        "bundle_out": "%{name}.bundle.tar",
    },
    provides = [
        SceneObjectTypeInfo,
        AssetInfo,
        AssetLocalInfo,
    ],
    implementation = _intrinsic_scene_object_impl,
)
