// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.cluster.v1;

import "intrinsic/util/status/extended_status.proto";

option go_package = "intrinsic/kubernetes/intrinsic_os/protos/v1/cluster_go_proto";

message Cluster {
  // The unique identifier of the cluster.
  string cluster_name = 1;
  // The display name of the cluster.
  string display_name = 2;

  // Status information about the cluster.
  repeated intrinsic_proto.status.ExtendedStatus extended_statuses = 23;
}

message GetClusterRequest {}

message RemoteAccessSettings {
  bool enabled = 1;
}

message GetRemoteAccessSettingsRequest {}

message UpdateRemoteAccessSettingsRequest {
  RemoteAccessSettings remote_access_settings = 1;
}

message UpdateRemoteAccessSettingsResponse {}
