# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//bazel:go_macros.bzl", "go_library")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "checks",
    srcs = ["checks.go"],
    importpath = "intrinsic/tools/inctl/cmd/doctor/checks/checks",
    deps = [
        "//intrinsic/tools/inctl/cmd/doctor/api",
        "//intrinsic/tools/inctl/cmd/doctor/checks/cluster_check:clustercheck",
        "//intrinsic/tools/inctl/cmd/doctor/checks/inctl_auth_check:inctlauthcheck",
        "//intrinsic/tools/inctl/cmd/doctor/checks/solution_check:solutioncheck",
    ],
)
