# Copyright 2023 Intrinsic Innovation LLC

load("@rules_cc//cc:cc_library.bzl", "cc_library")

exports_files([
    "zenohd_config.json5",
    "imw.h",
])

cc_library(
    name = "imw_interface",
    srcs = [],
    hdrs = [
        "imw.h",
    ],
    visibility = ["//visibility:public"],
)
