// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.assets.v1;

import "google/api/annotations.proto";
import "google/protobuf/any.proto";

option go_package = "intrinsic/assets/proto/v1/asset_configuration_go_proto";

service AssetConfigurationService {

  // Gets the recommended Asset configuration for the requested Asset instance,
  // or Skill parameters in case of a Skill node.
  //
  // The `RecommendAssetConfigurationResponse` may be a partially filled value
  // of the Asset's configuration proto or a Skill's parameters.
  //
  // The configurations will be recommended based on
  // the RecommendedConfigurationConfig.Source enum specified by
  // the Asset's manifest.
  //
  // Calling this service for Services and Hardware Devices that do not have
  // their configuration message types defined in their manifests will throw
  // a FAILED_PRECONDITION error.
  rpc RecommendAssetConfiguration(RecommendAssetConfigurationRequest)
      returns (RecommendAssetConfigurationResponse) {
    option (google.api.http) = {
      post: "/v1/assetConfiguration/{name}:recommendConfiguration"
      body: "*"
    };
  }

  // Batch version of `RecommendAssetConfiguration` which can be used to get
  // multiple recommended Asset configurations efficiently.
  rpc BatchRecommendAssetConfigurations(
      BatchRecommendAssetConfigurationsRequest)
      returns (BatchRecommendAssetConfigurationsResponse) {
    option (google.api.http) = {
      post: "/assetConfiguration/v1:batchRecommendConfigurations"
      body: "*"
    };
  }

  // Gets information on the Asset's configuration recommendation.
  rpc GetAssetRecommendationInfo(GetAssetRecommendationInfoRequest)
      returns (AssetRecommendationInfo) {
    option (google.api.http) = {
      get: "/v1/assetConfiguration/assetRecommendationInfo/{name}"
    };
  }
}

message RecommendAssetConfigurationResponse {
  // The recommended configuration value.
  //
  // This will be the same type as the Asset's configuration proto.
  google.protobuf.Any config = 1;
}

message RecommendAssetConfigurationRequest {
  // The identifier for the Asset in the Solution whose
  // configuration or parameters are to be populated.
  //
  // Provide the Asset ID here in case of a Skill, and the name of the
  // Asset instance in the Solution in case of Services and Hardware
  // Devices.
  string name = 1;

  // Input configuration on which to base the recommendation.
  optional google.protobuf.Any input_configuration = 2;
}

message BatchRecommendAssetConfigurationsRequest {
  // The individual recommendation requests to fulfill in a batch.
  repeated RecommendAssetConfigurationRequest requests = 1;
}

message BatchRecommendAssetConfigurationsResponse {
  // The individual responses for each request (in the same order).
  repeated RecommendAssetConfigurationResponse responses = 1;
}

// Information on whether an Asset has configuration recommendations.
message AssetRecommendationInfo {
  // The identifier of the Asset in the Solution.
  string name = 1;

  // Whether the Asset has configuration recommendations.
  bool has_recommendation = 2;
}

message GetAssetRecommendationInfoRequest {
  // The Asset identifier in the Solution to check recommendation
  // availability for.
  //
  // Provide the Asset ID here in case of a Skill, and the name of the
  // Asset instance in the Solution in case of Services and HardwareDevices.
  string name = 1;
}
