// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.assets.v1;

import "google/protobuf/any.proto";
import "intrinsic/scene/proto/v1/scene_object_config.proto";

option go_package = "intrinsic/assets/proto/v1/instance_config_go_proto";

// Configuration of an Asset instance.
message InstanceConfig {
  // Configuration of a SceneObject Asset instance.
  message SceneObjectInstanceConfig {
    // Configuration of the Asset's geometry and user metadata.
    intrinsic_proto.scene_object.v1.SceneObjectConfig scene_object_config = 1;
  }
  // Configuration of a Service Asset instance.
  message ServiceInstanceConfig {
    // Configuration passed to the Asset's service image.
    google.protobuf.Any service_config = 1;
    // Hostname on which the service should be run.
    optional string scheduled_node_hostname = 2;

  }
  // Configuration of a HardwareDevice Asset instance.
  message HardwareDeviceInstanceConfig {
    SceneObjectInstanceConfig scene_object = 1;
    ServiceInstanceConfig service = 2;
  }

  oneof variant {
    SceneObjectInstanceConfig scene_object = 1;
    ServiceInstanceConfig service = 2;
    HardwareDeviceInstanceConfig hardware_device = 3;
  }
}
