// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.assets.v1;

import "intrinsic/assets/proto/v1/asset.proto";
import "intrinsic/assets/proto/v1/asset_instances.proto";
import "intrinsic/world/proto/object_world_updates.proto";

option go_package = "intrinsic/assets/proto/v1/solution_go_proto";

// A Solution represents the Assets, Asset instances, and other information that
// define an automation solution in the Intrinsic platform.
message Solution {
  map<string, Asset> assets = 1;

  map<string, AssetInstance> instances = 2;

  repeated intrinsic_proto.world.ObjectWorldUpdate object_world_updates = 3;
}
