// Copyright 2023 Intrinsic Innovation LLC

#ifndef INTRINSIC_ICON_HAL_INTERFACES_ELECTRICAL_MOTOR_UTILS_H_
#define INTRINSIC_ICON_HAL_INTERFACES_ELECTRICAL_MOTOR_UTILS_H_

#include <cstdint>
#include <type_traits>

#include "absl/container/flat_hash_set.h"
#include "absl/strings/string_view.h"
#include "flatbuffers/detached_buffer.h"
#include "flatbuffers/flatbuffers.h"
#include "intrinsic/icon/hal/interfaces/electrical_motor.fbs.h"

namespace intrinsic_fbs {
flatbuffers::DetachedBuffer BuildElectricalMotorStatus();
flatbuffers::DetachedBuffer BuildElectricalMotorCommand(
    const absl::flat_hash_set<MotorControlMode>& supported_modes);

flatbuffers::DetachedBuffer BuildHomeCommand(int8_t method = 0,
                                             double offset = 0.0,
                                             double search_speed = 0.0,
                                             double creep_speed = 0.0,
                                             double acceleration = 0.0);
flatbuffers::DetachedBuffer BuildHomingStatus(
    intrinsic_fbs::HomingStatusFlag state =
        intrinsic_fbs::HomingStatusFlag::HomingUnknown,
    absl::string_view error_message = "");

bool SetMotorCommandCyclicPosition(ElectricalMotorCommand* command,
                                   double target_position,
                                   double velocity_feedforward = 0.0,
                                   double acceleration_feedforward = 0.0,
                                   double torque_feedforward = 0.0);
bool SetMotorCommandCyclicVelocity(ElectricalMotorCommand* command,
                                   double target_velocity,
                                   double torque_offset = 0.0);
bool SetMotorCommandCyclicTorque(ElectricalMotorCommand* command,
                                 double target_torque);
bool SetMotorCommandCyclicJointImpedance(ElectricalMotorCommand* command,
                                         double target_stiffness,
                                         double target_damping,
                                         double target_position,
                                         double target_velocity,
                                         double target_torque);
bool SetMotorCommandCyclicPositionTorque(ElectricalMotorCommand* command,
                                         double target_position,
                                         double velocity_offset = 0.0,
                                         double target_torque = 0.0);
bool SupportsMode(const ElectricalMotorCommand& command, MotorControlMode mode);

// Values of Enum classes (such as the ones generated by flatc with the
// --scoped-enums option) cannot be used with the bitwise operators we want to
// use for composing flag values. This makes casting them to a form where we can
// use those bitwise operators less verbose.
template <class EnumType>
typename std::underlying_type<EnumType>::type ToFlag(EnumType value) {
  return static_cast<typename std::underlying_type<EnumType>::type>(value);
}

// Sets the boolean values in ElectricalMotorStatus based on the status word.
// Note: There is no flag for homing, so this function does not touch that
// value.
void SetElectricalMotorStatus(ElectricalMotorStatus* motor_status,
                              uint16_t status_word);

// Verifies that the ElectricalMotorCommand has been set correctly, i.e. the
// message has the sub-command for the selected control mode.
bool CommandCorrectlySet(const ElectricalMotorCommand& motor_command);

}  // namespace intrinsic_fbs
#endif  // INTRINSIC_ICON_HAL_INTERFACES_ELECTRICAL_MOTOR_UTILS_H_
