// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace intrinsic_fbs;

table JointLimits {
  min_position:[double];
  max_position:[double];
  has_velocity_limits:bool = false;
  max_velocity:[double];
  has_acceleration_limits:bool = false;
  max_acceleration:[double];
  has_jerk_limits:bool = false;
  max_jerk:[double];
  has_effort_limits:bool = false;
  max_effort:[double];
}
