// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace intrinsic_fbs;

table JointPositionCommand {
  position:[double];
  velocity_feedforward:[double];
  acceleration_feedforward:[double];
}


table JointVelocityCommand {
  velocity:[double];
  acceleration_feedforward:[double];
}

table JointTorqueCommand {
  torque:[double];
}

// This is intended for robot drivers that implement acceleration resolved
// torque control. The joint acceleration would be used to solve the inverse
// dynamics for torque in the hardware module and the torque represents
// external forces applied to the end effector transformed into joint space.
table JointAccelerationAndTorqueCommand {
  acceleration:[double];
  torque:[double];
}

struct HandGuidingCommand {
  // Flatbuffers don't support empty structs.
  unused:bool;
}
