// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

include "intrinsic/icon/flatbuffers/transform_types.fbs";
include "intrinsic/icon/flatbuffers/matrix_types.fbs";

namespace intrinsic_fbs;

table RobotPayload {
  // Mass of the robot payload. Unit is kg.
  mass_kg:double;

  // Center of gravity of the robot payload relative to the robot flange/tip
  // frame. The unit is meters.
  tip_t_cog:Transform;

  // 3x3 symmetric inertia matrix of the robot payload expressed about the link
  // center of mass. Unit is kg*m^2.
  inertia:Matrix3d;
}

table OptionalRobotPayload {
  // If set, the robot payload is present.
  has_value: bool = false;

  // The value of the robot payload.
  value: RobotPayload;
}
