// Copyright 2023 Intrinsic Innovation LLC

syntax = "proto3";

package intrinsic_proto.util.proto.testing;

import "google/api/field_behavior.proto";
import "google/protobuf/any.proto";

option go_package = "intrinsic/util/proto/testing/field_behavior_test_go_proto";

message FieldBehaviorTestSubMessage {
  string regular_field = 1;
  optional string output_only_field = 2
      [(google.api.field_behavior) = OUTPUT_ONLY];
}

message FieldBehaviorTestMessage {
  string regular_field = 1;
  optional string output_only_field = 2
      [(google.api.field_behavior) = OUTPUT_ONLY];

  FieldBehaviorTestSubMessage nested = 3;
  repeated FieldBehaviorTestSubMessage repeated_nested = 4;
  repeated string repeated_output_only = 5
      [(google.api.field_behavior) = OUTPUT_ONLY];
  map<string, FieldBehaviorTestSubMessage> map_nested = 6;
  map<string, string> map_output_only = 7
      [(google.api.field_behavior) = OUTPUT_ONLY];

  google.protobuf.Any any_field = 8;
  bool output_only_bool = 9 [(google.api.field_behavior) = OUTPUT_ONLY];
  optional uint32 output_only_uint32 = 10
      [(google.api.field_behavior) = OUTPUT_ONLY];
  string non_optional_output_only_string = 11
      [(google.api.field_behavior) = OUTPUT_ONLY];
}
