// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.geometry;

option go_package = "intrinsic/geometry/proto/geometry_storage_refs_go_proto";

// GeometryStorageRefs is intended to be an (mostly) opaque container of
// references to storage objects e.g. CAS URIs. The constituent fields provide
// no guarantees of uniqueness.
message GeometryStorageRefs {
  string fingerprint = 1;
  // A reference to the stored geometry proto e.g. a CAS URI.
  string geometry_ref = 2;
  // A reference to the stored renderable proto e.g. a CAS URI.
  string renderable_ref = 3;
}
