// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.geometry;

import "intrinsic/geometry/proto/primitives.proto";
import "intrinsic/geometry/proto/triangle_mesh.proto";

option go_package = "intrinsic/geometry/proto/lazy_exact_geometry_go_proto";

// Computational geometry representation of Geometry.
message LazyExactGeometry {
  // The mesh representation of this Geometry.
    TriangleMesh triangle_mesh = 6;

  // An optional set of primitives that represent the geometry.
  PrimitiveShapeSet primitive_set = 5;

  reserved 2, 4;
  reserved "mesh_octree", "mesh_octree_wrapping";
}

// A primitives based representation of a geometric shape.
message PrimitiveShape {
  oneof shape {
    Box box = 1;
    Cylinder cylinder = 2;
    Sphere sphere = 3;
    Ellipsoid ellipsoid = 4;
    Capsule capsule = 5;
    Frustum frustum = 6;
  }
}

// A set of primitives grouped together.
message PrimitiveShapeSet {
  repeated PrimitiveShape primitives = 1;
}
