// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.geometry;

import "intrinsic/geometry/proto/octree.proto";

option go_package = "intrinsic/geometry/proto/mesh_octree_wrapping_go_proto";

// Wrapping context for describing how a octree wraps a mesh. This data
// structure contains both the octree and the associations between octree voxels
// and the primitives contained in the corresponding mesh.
message MeshOctreeWrapping {
  // The octree structure.
  Octree octree = 1;

  message MortonToPrimitiveEntry {
    uint64 code = 1;
    repeated int32 primitives = 2;
  }

  // The associations between the voxels and the primitives in the mesh.
  repeated MortonToPrimitiveEntry morton_to_primitives = 3;
}
