// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.skills;

import "intrinsic/math/proto/pose.proto";
import "intrinsic/world/proto/entity_search.proto";

option go_package = "intrinsic/skills/proto/motion_targets_go_proto";

message CartesianMotionTarget {
  // The frame on the tool that you want to move to align with frame and offset.
  intrinsic_proto.world.EntitySearchCriteria tool = 1;

  // The tool target frame. If an offset with respect to this frame is
  // specified, the tool target is the frame plus the applied offset.
  intrinsic_proto.world.EntitySearchCriteria frame = 2;
  // Optional, you can place an offset between frame
  // and tool.
  intrinsic_proto.Pose offset = 3;
}
