// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.skills;

import "intrinsic/executive/proto/behavior_tree.proto";
import "intrinsic/skills/proto/skills.proto";

option go_package = "intrinsic/skills/proto/skill_registry_config_go_proto";

message SkillRegistration {
  intrinsic_proto.skills.SkillHandle validate_handle = 1;
  intrinsic_proto.skills.SkillHandle project_handle = 2;
  intrinsic_proto.skills.SkillHandle execute_handle = 3;
  intrinsic_proto.skills.SkillHandle skill_info_handle = 5;

  intrinsic_proto.skills.Skill skill = 4;
}

message BehaviorTreeRegistration {
  intrinsic_proto.executive.BehaviorTree behavior_tree = 1;
}

message SkillRegistryConfig {
  repeated SkillRegistration skills = 2;
  repeated BehaviorTreeRegistration behavior_trees = 3;
}
