// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.geometry.v1;

import "intrinsic/math/proto/vector2.proto";
import "intrinsic/math/proto/vector3.proto";

option go_package = "intrinsic/geometry/proto/v1/axis_aligned_bounding_box_go_proto";

// Generic bounding box for the n-dimensional case.
// For 2D and 3D, use specialized types (see below).
// Note that the number of dimensions is only implicitly encoded in the length
// of min_points and max_points (when set). However, we also consider a bounding
// box valid when min_points and max_points are empty (this corresponds then to
// an empty bounding box).
message AxisAlignedBoundingBox {
  repeated double min_points = 1;
  repeated double max_points = 2;
}

// Bounding box for 2D.
message AxisAlignedBoundingBox2 {
  intrinsic_proto.Vector2 min = 1;
  intrinsic_proto.Vector2 max = 2;
}

// Bounding box for 3D.
message AxisAlignedBoundingBox3 {
  intrinsic_proto.Vector3 min = 1;
  intrinsic_proto.Vector3 max = 2;
}
