// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.geometry.v1;

import "intrinsic/geometry/proto/v1/geometry_options.proto";
import "intrinsic/geometry/proto/v1/octree_wrapping.proto";
import "intrinsic/geometry/proto/v1/point_cloud.proto";
import "intrinsic/geometry/proto/v1/transformed_primitive_shape_set.proto";
import "intrinsic/geometry/proto/v1/triangle_mesh.proto";

option go_package = "intrinsic/geometry/proto/v1/exact_geometry_go_proto";

// Computational geometry representation of Geometry.
message ExactGeometry {
  // The data representation of this Geometry.
  oneof data {
    TransformedPrimitiveShapeSet primitive_set = 1;

    // The mesh representation of this Geometry.
    TriangleMesh triangle_mesh = 2;

    // Point cloud data for this geometry instance.
    PointCloud point_cloud = 3;
  }

  // An optional Octree based wrapping that segments the raw data into an octree
  optional OctreeWrapping octree_wrapping = 4;

  // Runtime options for this geometry.
  GeometryOptions options = 5;
}
