// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.geometry.v1;

option go_package = "intrinsic/geometry/proto/v1/geometry_options_go_proto";

// Runtime options for a Geometry.
message GeometryOptions {
  // If set, the octree will be filled on the inside when constructing the
  // octree for distance queries. This is only used when generating new octree
  // wrappings from an existing mesh or point cloud. This is not used when
  // loading a pre-existing octree wrapping like the one stored in the
  // ExactGeometry proto.
  optional bool fill_inside_for_distance_queries = 1;

  // Optional parameter to specify the resolution for convex decomposition.
  // This parameter only affects how the geometry is simulated in Gazebo and is
  // typically used for optimizing collision meshes.
  // If the associated geometry is not a mesh type, this field has no effect.
  optional uint32 simulation_convex_decomposition_resolution = 2;
}
