// Copyright 2023 Intrinsic Innovation LLC

syntax = "proto3";

package intrinsic_proto.geometry.v1;

option go_package = "intrinsic/geometry/proto/v1/geometry_options_go_proto";

// Runtime options for a Geometry.
message GeometryOptions {
  // If set, the octree will be filled on the inside when constructing the
  // octree for distance queries. This is only used when generating new octree
  // wrappings from an existing mesh or point cloud. This is not used when
  // loading a pre-existing octree wrapping like the one stored in the
  // ExactGeometry proto.
  optional bool fill_inside_for_distance_queries = 1;

  // Optional parameter to specify the resolution for convex decomposition.
  // This parameter only affects how the geometry is simulated in Gazebo and is
  // typically used for optimizing collision meshes.
  // If the associated geometry is not a mesh type, this field has no effect.
  optional uint32 simulation_convex_decomposition_resolution = 2;
}
