// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.geometry.v1;

import "intrinsic/geometry/proto/v1/exact_geometry.proto";
import "intrinsic/geometry/proto/v1/renderable.proto";

option go_package = "intrinsic/geometry/proto/v1/inline_geometry_go_proto";

message InlineGeometry {
  // The computational geometry representation.
  ExactGeometry exact_geometry = 1;

  // The optional renderable data.
  oneof renderable_type {
    // If renderable is specified then this proto contains a unique (user
    // provided) renderable that should be maintained.
    Renderable renderable = 2;
    // If generated_renderable is specified then this proto contains a cached
    // generated renderable and does not have to be maintained.
    Renderable generated_renderable = 3;
  }
}
