// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.geometry.v1;

import "intrinsic/geometry/proto/v1/geometric_transform.proto";
import "intrinsic/geometry/proto/v1/geometry.proto";

option go_package = "intrinsic/geometry/proto/v1/transformed_geometry_go_proto";

message TransformedGeometry {
  // The geometric data for the shape.
  Geometry geometry = 1;

  // The geometric transform from the reference frame to the shape.
  GeometricTransform ref_t_shape = 2;
}
