# Copyright 2023 Intrinsic Innovation LLC

"""Internal module containing helpers for the behavior_tree module.

Do not import this module directly - use the forwarded names defined in
intrinsic.solutions.behavior_tree.
"""

from __future__ import annotations

from typing import Any as AnyType
import uuid

from google.protobuf import descriptor_pb2

from intrinsic.util.proto import descriptors


def generate_unique_node_id() -> int:
  """Generates a unique node ID suitable to use in a behavior tree.

  Returns:
    32 bit portion as int from an UUID that can be used as a randomized node ID.
  """
  uid = uuid.uuid4()
  uid_128 = uid.int
  # The proto only specifies uint32, so a 128-bit UUID wouldn't fit. XOR
  # this together to retain sufficient randomness to prevent collisions.
  # Node Ids must be unique only within the behavior tree that is being
  # created.
  uid_32 = (
      (uid_128 & 0xFFFFFFFF)
      ^ (uid_128 & (0xFFFFFFFF << 32)) >> 32
      ^ (uid_128 & (0xFFFFFFFF << 64)) >> 64
      ^ (uid_128 & (0xFFFFFFFF << 96)) >> 96
  )
  return int(uid_32)


def build_file_descriptor_set(
    msg: type[AnyType],
) -> tuple[str, descriptor_pb2.FileDescriptorSet]:
  """Build a FileDescriptorSet proto from a given proto class.

  The given proto must have a DESCRIPTOR property. This is usually the case,
  when it is generated by the build system and imported.

  Args:
    msg: The proto message to generate a descriptor set for.

  Returns:
    A tuple that contains the full name of the message and the FileDescriptorSet
    proto with the extracted transitive file descriptor set.
  """

  if not hasattr(msg, 'DESCRIPTOR'):
    raise AttributeError(
        'Passed message does not have a DESCRIPTOR. Ensure that the proto is'
        ' build and imported correctly.'
    )

  return msg.DESCRIPTOR.full_name, descriptors.gen_file_descriptor_set(
      msg.DESCRIPTOR
  )


def get_single_message_name_from_file(
    desc_set: descriptor_pb2.FileDescriptorSet, filename
) -> str | None:
  """Returns the single message name defined in a FileDescriptorSet file.

  Returns the full name of the message type which is defined in the given file
  of the given FileDescriptorSet. Returns None if the file is not found. Raises
  an assertion error if the file does not define exactly one message type.

  Args:
    desc_set: The FileDescriptorSet in which to search.
    filename: The name of the file in which to search for the message type.
  """
  for file in desc_set.file:
    if file.name == filename:
      assert len(file.message_type) == 1
      return file.package + '.' + file.message_type[0].name
  return None
