# Copyright 2023 Intrinsic Innovation LLC

# C++ ACL helpers

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = [
    "//visibility:public",
])

cc_library(
    name = "cookie_names",
    hdrs = ["cookie_names.h"],
)

cc_library(
    name = "header_names",
    hdrs = ["header_names.h"],
)
