// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.assets.build_defs;

import "google/protobuf/descriptor.proto";
import "intrinsic/assets/proto/asset_type.proto";
import "intrinsic/assets/proto/id.proto";
import "intrinsic/assets/proto/v1/instance_config.proto";

option go_package = "intrinsic/assets/build_defs/asset_go_proto";

message AssetInfo {
  // The asset's type.
  intrinsic_proto.assets.AssetType asset_type = 1;
  // The asset ID.
  intrinsic_proto.assets.Id id = 2;
  // A file descriptor set containing definitions for protos used by the asset.
  optional google.protobuf.FileDescriptorSet file_descriptor_set = 3;

  reserved 199;
}

message AssetLocalInfo {
  // The asset's type.
  intrinsic_proto.assets.AssetType asset_type = 1;
  // The asset ID.
  intrinsic_proto.assets.Id id = 2;
  // This is the Bazel runfiles path to the bundle file.
  string bundle_runfiles_path = 5;

  reserved 3, 4, 199;
  reserved "bundle_short_path", "bundle_path";
}

message AssetCatalogRefInfo {
  // The asset's type.
  intrinsic_proto.assets.AssetType asset_type = 1;
  // The asset ID and version.
  intrinsic_proto.assets.IdVersion id_version = 2;

  reserved 199;
}

message AssetInstanceInfo {
  // The name of this asset instance.
  string name = 1;
  // The Asset backing the Asset instance.  This is the local name of the Asset
  // as specified in the Assets map of the Solution.  By convention, this is the
  // id of the Asset.
  string asset = 2;
  // This is the Bazel runfiles path to the config file.
  string config_runfiles_path = 3;
  // The parsed config of the asset instance.
  intrinsic_proto.assets.v1.InstanceConfig parsed = 6;

  reserved 4, 5, 7;
  reserved "instance_name", "required_node_hostname", "text_proto",
      "data_files", "config";
}
