# Copyright 2023 Intrinsic Innovation LLC

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "gen_http_bridge_bzl",
    srcs = ["gen_http_bridge.bzl"],
    visibility = ["//visibility:public"],
)
