# Copyright 2023 Intrinsic Innovation LLC

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

bzl_library(
    name = "go_grpc_http_library_bzl",
    srcs = ["go_grpc_http_library.bzl"],
    visibility = ["//visibility:private"],
    deps = ["//bazel:go_macros"],
)
