// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.storage.artifacts.v1;

option go_package = "intrinsic/storage/artifacts/proto/v1/articat_go_proto";

// Service alias for intrinsic_proto.storage.artifacts.v1.ArtifactServiceApi
// It is here so the name cannot be stolen from us by some other service
// causing a name collision. There should never be a real instance of this
// service running anywhere.
service ArtifactCatalogService {}
