# Copyright 2023 Intrinsic Innovation LLC

# proto-file: intrinsic/icon/hal/proto/hardware_module_config.proto
# proto-message: intrinsic_proto.icon.HardwareModuleConfig
# Custom configuration to test the configuration upload of
# https://flowstate.intrinsic.ai/docs/apis/client_libraries/icon_extensions/custom_hardware_modules/

name: "my_custom_hwm"
disable_malloc_guard: true
control_frequency_hz: 50
