# Copyright 2023 Intrinsic Innovation LLC

exports_files(
    srcs = [
        "empty_notebook.ipynb.template",
    ],
    visibility = [
        "//intrinsic/tools/inctl/cmd/notebook:__subpackages__",
    ],
)
