// Copyright 2023 Intrinsic Innovation LLC

package organization

import (
	"context"
	"fmt"
	"time"

	"intrinsic/tools/inctl/util/accounts/accounts"
	"intrinsic/tools/inctl/util/agents"
	"intrinsic/tools/inctl/util/orgutil"

	"github.com/spf13/cobra"

	accresourcemanager1pb "intrinsic/kubernetes/accounts/service/api/resourcemanager/v1/resourcemanager_go_proto"

	lropb "cloud.google.com/go/longrunning/autogen/longrunningpb"
)

func init() {
	organizationsInit(organizationCmd)
}

func organizationsInit(root *cobra.Command) {
	createCmd.Flags().StringVar(&flagOrgDisplayName, "display-name", "", "The display name of the organization to create.")
	createCmd.MarkFlagRequired("display-name")
	createCmd.Flags().StringVar(&flagParent, "parent", "", "The parent organization under which the new organization will be created. Alternatively, --org can also be used.")
	createCmd.MarkFlagRequired("parent")
	root.AddCommand(createCmd)

	deleteCmd.Flags().BoolVar(&flagYes, "yes", false, "Skip the confirmation prompt and directly delete the organization.")
	root.AddCommand(deleteCmd)

	root.AddCommand(getCmd)
}

var createCmdHelp = `
Create a new empty organization.

Creating a new organization sets up isolated infrastructure and can take up to 15 minutes to complete.
You must have permissions to create a new organization.
Use the --parent flag (or alternatively the --org flag) to specify the parent organization under which the new organization will be created.

Example:

		inctl organization create --display-name="My Organization" --parent=myorg
`

var createCmd = &cobra.Command{
	Use:   "create",
	Short: "Create a new organization.",
	Long:  createCmdHelp,
	RunE: func(cmd *cobra.Command, args []string) error {
		parent := flagParent
		if parent == "" {
			parent = vipr.GetString(orgutil.KeyOrganization)
		}
		if parent == "" {
			return fmt.Errorf("the --parent (or --org) flag is required for this command to specify a parent for the organization to create")
		}
		if parent == "intrinsic" {
			return fmt.Errorf("the parent organization cannot be 'intrinsic'")
		}
		var parentOrg string
		if parent != "" {
			parentOrg = addPrefix(parent, orgPrefix)
		}

		ctx := cmd.Context()
		cl, err := newResourceManagerV1Client(ctx)
		if err != nil {
			return err
		}

		req := accresourcemanager1pb.CreateOrganizationRequest{
			OrganizationId: "", // randomly generated by the server
			Organization: &accresourcemanager1pb.Organization{
				DisplayName:        flagOrgDisplayName,
				ParentOrganization: parentOrg,
			},
		}
		if flagDebugRequests {
			protoPrint(&req)
		}

		fmt.Printf("Creating organization (display name: %q). Note: this operation may take up to 15 minutes to complete...\n", flagOrgDisplayName)

		op, err := cl.CreateOrganization(ctx, &req)
		if err != nil {
			return fmt.Errorf("failed to create organization: %w", err)
		}
		if flagDebugRequests {
			protoPrint(op)
		}
		op, err = accounts.WaitForOperation(ctx, cl.GetOperation, op, 15*time.Minute)
		if err != nil {
			return fmt.Errorf("failed to wait for operation: %w", err)
		}
		if flagDebugRequests {
			protoPrint(op)
		}
		operr := op.GetError()
		if operr != nil {
			return fmt.Errorf("failed to create organization: %v", operr)
		}
		if op.GetResult() != nil {
			res := op.GetResult().(*lropb.Operation_Response).Response
			org := &accresourcemanager1pb.Organization{}
			if err := res.UnmarshalTo(org); err != nil {
				return fmt.Errorf("failed to unmarshal organization: %w", err)
			}
			fmt.Printf("Created organization with identifier %q.\n", org.GetName())
		}
		return nil
	},
}

var deleteCmdHelp = `
Delete an organization.

The delete command marks the organization as soft-deleted. A soft-deleted organization can be
recovered for at least 30 days by contacting support.

Example:

		inctl organization delete myorg
		inctl organization delete --org=myorg
`

var deleteCmd = &cobra.Command{
	Use:   "delete [organization]",
	Short: "Delete an organization.",
	Long:  deleteCmdHelp,
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		org, err := resolveOrgArgOrFlag(args)
		if err != nil {
			return err
		}
		agents.CheckAndExit(cmd)
		ctx := cmd.Context()
		cl, err := newResourceManagerV1Client(ctx)
		if err != nil {
			return err
		}
		// if the user did not specify --yes, ask for confirmation
		// also skips client-side input validations (like org state)
		if !flagYes {
			if err := confirmDelete(ctx, cl, org); err != nil {
				return err
			}
		}
		req := accresourcemanager1pb.DeleteOrganizationRequest{
			Name: addPrefix(org, orgPrefix),
		}
		if flagDebugRequests {
			protoPrint(&req)
		}
		fmt.Printf("Deleting organization %q ...\n", org)
		op, err := cl.DeleteOrganization(ctx, &req)
		if err != nil {
			return fmt.Errorf("failed to delete organization: %w", err)
		}
		if flagDebugRequests {
			protoPrint(op)
		}
		op, err = accounts.WaitForOperation(ctx, cl.GetOperation, op, 10*time.Minute)
		if err != nil {
			return fmt.Errorf("failed to wait for operation: %w", err)
		}
		if flagDebugRequests {
			protoPrint(op)
		}
		return nil
	},
}

var getCmdHelp = `
Get details of an organization.

Example:

		inctl organization get myorg
		inctl organization get --org=myorg
`

var getCmd = &cobra.Command{
	Use:   "get [organization]",
	Short: "Get details of an organization.",
	Long:  getCmdHelp,
	Args:  cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		org, err := resolveOrgArgOrFlag(args)
		if err != nil {
			return err
		}
		ctx := cmd.Context()
		cl, err := newResourceManagerV1Client(ctx)
		if err != nil {
			return err
		}
		req := &accresourcemanager1pb.GetOrganizationRequest{
			Name: addPrefix(org, orgPrefix),
		}
		if flagDebugRequests {
			protoPrint(req)
		}
		resp, err := cl.GetOrganization(ctx, req)
		if err != nil {
			return fmt.Errorf("failed to get organization: %w", err)
		}
		protoPrint(resp)
		return nil
	},
}

// confirmDelete first fetches the organization to check if it exists and to display its display name to the user.
// Also performs some client-side input validations (like org state).
func confirmDelete(ctx context.Context, cl accounts.ResourceManagerV1Client, org string) error {
	o, err := cl.GetOrganization(ctx, &accresourcemanager1pb.GetOrganizationRequest{Name: addPrefix(org, orgPrefix)})
	if err != nil {
		return fmt.Errorf("failed to find organization %q: %w", org, err)
	}
	if o.GetState() == accresourcemanager1pb.Organization_DELETED {
		return fmt.Errorf("organization %q is already deleted", org)
	}
	// if the user did not specify --yes, ask for confirmation
	if !flagYes {
		fmt.Printf("You are about to delete organization %q (%q). Please type the organization identifier to confirm: ",
			org, o.DisplayName)
		var input string
		if _, err := fmt.Scanln(&input); err != nil {
			return fmt.Errorf("failed to read input: %w", err)
		}
		if input != org {
			return fmt.Errorf("input does not match organization identifier %q", org)
		}
	}
	return nil
}
