# Copyright 2023 Intrinsic Innovation LLC

# proto-file: intrinsic/assets/services/proto/service_manifest.proto
# proto-message: intrinsic_proto.services.ServiceManifest

metadata {
  id {
    package: "ai.intrinsic.fieldbus.ethercat"
    name: "device_service"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "Generic EtherCAT Device service"
  }
  display_name: "Generic EtherCAT Device Service"
}
service_def {
  service_proto_prefixes: "/intrinsic_proto.fieldbus.ethercat.device_service.v1.DeviceService/"
  service_proto_prefixes: "/intrinsic_proto.services.v1.ServiceState/"
  real_spec: {
    image: {
      archive_filename: "device_service_image.tar"
    }
  }
  sim_spec: {
    image: {
      archive_filename: "device_service_image.tar"
    }
  }
  supports_dynamic_reconfiguration: false
  supports_service_state: true
}
