# Copyright 2026 Intrinsic Innovation LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# proto-file: https://github.com/intrinsic-ai/sdk/blob/main/intrinsic/assets/services/proto/service_manifest.proto
# proto-message: intrinsic_proto.services.ServiceManifest

metadata {
  id {
    package: "com.example"
    name: "inventoryservice"
  }
  vendor {
    display_name: "Intrinsic"
  }
  documentation {
    description: "Offers gRPC API for managing inventory."
  }
  display_name: "Inventory Service"
}
service_def {
  http_config: {}
  service_proto_prefixes: "/intrinsic_proto.httpjson.v1.InventoryService/"
  real_spec {
    image {
      archive_filename: "tarball.tar"
    }
    extra_images {
      archive_filename: "inventoryserver_http_image.tar"
    }
  }
  sim_spec {
    image {
      archive_filename: "tarball.tar"
    }
    extra_images {
      archive_filename: "inventoryserver_http_image.tar"
    }
  }
}
