// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.eoat;

import "intrinsic/hardware/gpio/v1/signal.proto";

option go_package = "intrinsic/hardware/gripper/eoat/gripper_config_go_proto";

message SignalConfig {
  // `oneof` is used to allow for future handling of more types
  oneof type {
    // Map of signal names to bool values. E.g. {"/signal/name", true}.
    // For actuation (e.g. grasp, release, etc.), the bool values
    // are written to the port address.
    // For sensing (e.g. gripping_indicated), the bool values are matched
    // against the current values.
    intrinsic_proto.gpio.v1.SignalValueSet value_set = 1;
  }
}

message PinchGripperConfig {
  SignalConfig grasp = 2;
  SignalConfig release = 3;
  SignalConfig gripping_indicated = 4;

  // Whether the gripper is closed when all joints are at their lower limit. Set
  // it to false (default) if the gripper is open when all joints are at their
  // lower limit. This parameter is used to correctly update the digital twin
  // when the gripper is commanded to grasp or release.
  bool is_default_closed = 5;
}

message SuctionGripperConfig {
  SignalConfig grasp = 2;
  SignalConfig release = 3;
  // Turn on blow off
  SignalConfig blowoff_on = 4;
  // Turn off blow off
  SignalConfig blowoff_off = 6;
  SignalConfig gripping_indicated = 5;
}
