// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.accounts.tokens.v2;

import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

option go_package = "intrinsic/kubernetes/accounts/service/api/tokens/v2/tokens_go_proto";

message GetIPCTokenRequest {
  IPCCredential credential = 1;
}

message GetIPCTokenResponse {
  string ipc_token = 1;
}

message IPCCredential {
  oneof oneOf {
    RobotJWT robot_jwt = 1;
  }
}

message RobotJWT {
  // The robot JWT issued by the metadata server to exchange for an IPC token.
  string jwt = 1;
}

message PingResponse {
  google.protobuf.Timestamp timestamp = 1;
}

service AccountsTokensService {
  // Ping returns the current timestamp. Can be used for latency and
  // availability probes.
  rpc Ping(google.protobuf.Empty) returns (PingResponse) {
    option (google.api.http) = {
      get: "/tokens/v2:ping"
    };
  }

  // GetIPCToken returns an IPC token for the given credential.
  // With the returned token an IPC can access the Intrinsic cloud platform.
  rpc GetIPCToken(GetIPCTokenRequest) returns (GetIPCTokenResponse) {
    option (google.api.http) = {
      post: "/tokens/v2/ipctoken"
      body: "*"
    };
  }
}
