# Copyright 2023 Intrinsic Innovation LLC

# Services for the manipulation package.

package(
    default_visibility = [
        "//intrinsic/logging:__subpackages__",
        "//intrinsic/manipulation:__subpackages__",
    ],
)
