# Copyright 2023 Intrinsic Innovation LLC

# proto-file: intrinsic/skills/proto/skill_manifest.proto
# proto-message: intrinsic_proto.skills.SkillManifest

id {
  package: "ai.intrinsic"
  name: "kv_store_set_string"
}
display_name: "KVStore Set String"
vendor {
  display_name: "Intrinsic"
}
documentation {
  description: "Sets a string value in the Intrinsic Runtime KVStore service."
}
options {
  supports_cancellation: false
  cc_config {
    create_skill: "::intrinsic::skills::KvStoreSetStringSkill::CreateSkill"
  }
}
parameter {
  message_full_name: "intrinsic_proto.skills.KvStoreSetStringParams"
}
return_type {
  message_full_name: "intrinsic_proto.skills.KvStoreSetStringResult"
}
