# Copyright 2023 Intrinsic Innovation LLC

package(default_visibility = [
    "//intrinsic/assets:__subpackages__",
    "//intrinsic/frontend:__subpackages__",
    "//intrinsic/kubernetes:__subpackages__",
    "//intrinsic/skills/tools/skill:__subpackages__",
    "//intrinsic/solutions:__subpackages__",
    "//intrinsic/tools/inctl:__subpackages__",
])
