// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package intrinsic_proto.workcell_spec.v1;

option go_package = "intrinsic/kubernetes/workcell_spec/proto/image_go_proto";

message Image {
  // fully qualified url to container registry, e.g. 'gcr.io/<project-id>'
  string registry = 1;
  // image name, will also be used in the template for the resources that run
  // the image (e.g. pod or deployment)
  string name = 2;
  // image ref, e.g. '@sha256:<sha>' or ':<tag>'
  string tag = 3;
  // private registry auth, e.g. for gcr.io use:
  //   user=oauth2accesstoken
  //   password="$(gcloud auth application-default print-access-token)"
  string auth_user = 4;
  string auth_password = 5;
}
