# Copyright 2023 Intrinsic Innovation LLC

load("//intrinsic/icon/fieldbus/ethercat/build_defs:eni_data.bzl", "intrinsic_eni_data")

package(default_visibility = ["//visibility:public"])

intrinsic_eni_data(
    name = "1motor_eni",
    asset_name = "yskw_1motor",
    asset_package = "ai.intrinsic.ethercat.eni",
    display_name = "[ENI] 1 Motor",
    eni_file = ":1motor.eni",
    vendor_display_name = "Intrinsic",
)
