// Copyright 2026 Intrinsic Innovation LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package onprem_to_line_router_relay;

option go_package = "intrinsic/platform/pubsub/connect/onprem/onprem_to_line_router_relay_service/onprem_to_line_router_relay_service_go_proto";

// Configuration for the relay router service that connects
// the onprem Zenoh router to the line-level router in the cloud.
message OnpremToLineRouterRelayServiceConfig {
  string org_id = 1;
  string line_id = 2;
}
